version: '2'
services:

  input:
    container_name: Input-Service
    build: ./input
    ports:
      - "8081:8081"
    depends_on:
      - "kafka"

  processor:
    container_name: Processor-Service
    build: ./processor
    ports:
      - "8082:8082"
    depends_on:
      - "kafka"

  output:
    container_name: Output-Service
    build: ./output
    ports:
      - "8083:8083"
    depends_on:
      - "kafka"

  zookeeper:
    container_name: Zookeeper-Kafka
    image: confluentinc/cp-zookeeper:latest
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    container_name: Kafka-Kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - "zookeeper"
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock